# Generated by Django 4.1.1 on 2022-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("empemail", models.EmailField(blank=True, max_length=50, null=True)),
                ("bunit", models.CharField(max_length=50)),
                ("bmpposition", models.CharField(blank=True, max_length=50, null=True)),
                ("bossname", models.CharField(blank=True, max_length=50, null=True)),
                ("bossmail", models.EmailField(max_length=50)),
                ("contractstartdate", models.DateField(blank=True, null=True)),
                ("contractenddate", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
