# Generated by Django 4.1.1 on 2022-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_empleados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleados",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
