# Generated by Django 4.1.1 on 2022-10-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_empleados_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("QUINTA CATEGORIA", "Quinta Categoria"),
                            ("RECIBO POR HONORARIOS", "Recibo por honorarios"),
                            (
                                "PRACTICAS PRE PROFESIONALES",
                                "Practicas pre profesionales",
                            ),
                            ("PRACTICAS PROFESIONALES", "Practicas profesionales"),
                        ],
                        max_length=50,
                    ),
                ),
                ("correlativo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "plazo_renovacion",
                    models.CharField(
                        choices=[
                            ("1 MES", "1 mes"),
                            ("2 MESES", "2 meses"),
                            ("3 MESES", "3 meses"),
                            ("4 MESES", "4 meses"),
                            ("5 MESES", "5 meses"),
                            ("6 MESES", "6 meses"),
                            ("12 MESES", "12 meses"),
                            ("NO RENOVADO", "No renovar"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "motivo_cese",
                    models.CharField(
                        choices=[
                            ("PERIODO DE PRUEBA", "Periodo de prueba"),
                            (
                                "TERMINO DE CONTRATO A SOLICITUD DEL JEFE INMEDIATO",
                                "Termino de contrato a solicitud del jefe inmediato",
                            ),
                            (
                                "TERMINO DE CONTRATO A SOLICITUD DEL COLABORADOR",
                                "Termino de contrato a solicitu del colaborador",
                            ),
                            ("RENUNCIA", "Renuncia"),
                            ("MUTUO DISENSO", "Mutuo disenso"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comentario", models.TextField()),
                (
                    "Empleados",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.database",
                    ),
                ),
            ],
        ),
    ]
