# Generated by Django 4.1.1 on 2022-10-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_database_comentario_database_correlativo_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="database", table="Database",),
    ]
