# Generated by Django 4.1.1 on 2022-10-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_database_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="database", table=None,),
    ]
