# Generated by Django 4.1.1 on 2022-10-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_database_renovacion"),
    ]

    operations = [
        migrations.RemoveField(model_name="database", name="renovacion",),
    ]
