# Generated by Django 4.1.1 on 2022-10-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_database_renovacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="plazo_renovacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 mes"),
                    ("2", "2 meses"),
                    ("3", "3 meses"),
                    ("4", "4 meses"),
                    ("5", "5 meses"),
                    ("6", "6 meses"),
                    ("12", "12 meses"),
                    ("0", "No renovar"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="plazo_renovacion",
            field=models.CharField(
                choices=[
                    ("1", "1 mes"),
                    ("2", "2 meses"),
                    ("3", "3 meses"),
                    ("4", "4 meses"),
                    ("5", "5 meses"),
                    ("6", "6 meses"),
                    ("12", "12 meses"),
                    ("0", "No renovar"),
                ],
                max_length=50,
            ),
        ),
    ]
