# Generated by Django 4.1.1 on 2022-10-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_database_plazo_renovacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="comentario_rrhh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="comentario",
            field=models.TextField(blank=True, null=True),
        ),
    ]
