# Generated by Django 4.1.1 on 2022-11-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_database_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="database", table="empleado",),
    ]
