# Generated by Django 4.1.1 on 2022-11-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_database_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="statusrenovacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pendiente", "PENDIENTE"),
                    ("Enviado por el colaborador", "ENVIADO POR EL COLABORADOR"),
                    ("Firmado por el colaborador", "FIRMADO POR EL COLABORADOR"),
                    ("Cese", "CESE"),
                    ("Indefinido", "INDEFINIDO"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
