# Generated by Django 4.1.1 on 2022-11-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_database_statusrenovacion"),
    ]

    operations = [
        migrations.AlterModelOptions(name="database", options={"ordering": ("id",)},),
    ]
